# Application Configuration for Enterprise Automation Framework
# This file contains all the settings for your framework

# Spring Boot Configuration
spring:
  application:
    name: enterprise-automation-framework
  
  # Profile Configuration (we'll use this for different environments)
  profiles:
    active: local  # Options: local, ci, dev, staging, prod

# Framework Configuration
automation:
  # Web Testing Configuration
  web:
    browser: chrome           # Options: chrome, firefox, edge, safari
    headless: false          # true for CI/CD, false for local development
    timeout: 30              # Default wait timeout in seconds
    window-size: "1920,1080"  # Browser window size (e.g., "1920,1080" for 1920x1080)
    # New: Add browser capabilities for advanced settings
    capabilities:
      acceptInsecureCerts: true
      # Example for Chrome
      chrome:
        # New: Centralized all Chrome arguments here
        args:
          - "--disable-gpu"
          - "--no-sandbox"
          - "--disable-dev-shm-usage"
          - "--disable-extensions"
          - "--start-maximized"
      # Firefox Options
      moz:firefoxOptions:
        args: ["-headless"] # Note: Firefox uses a single hyphen for headless mode.
      # Microsoft Edge Options (similar to Chrome)
      ms:edgeOptions:
        args:
          - "--disable-gpu"
          - "--no-sandbox"
          - "--disable-dev-shm-usage"
          - "--start-maximized"

  # API Testing Configuration  
  api:
    base-url: "https://jsonplaceholder.typicode.com"
    timeout: 15
    retry-count: 3
    # New: Add default headers for all API requests
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    
  # Database Configuration
  database:
    url: "jdbc:mysql://localhost:3306/testdb"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver: "com.mysql.cj.jdbc.Driver"
    
  # Mobile Testing Configuration
  mobile:
    platform: android        # Options: android, ios
    device-name: "Pixel_6"
    app-path: "/path/to/app.apk"
    
  # Reporting Configuration
  reporting:
    allure-results: "target/allure-results"
    screenshots: true
    video-recording: false

# Logging Configuration
logging:
  level:
    com.enterprise.automation: INFO
    # New: Set specific logging for REST Assured or other clients
    io.restassured: DEBUG
    org.springframework: WARN
    org.selenium: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Local Environment Profile
spring:
  config:
    activate:
      on-profile: local
automation:
  web:
    headless: false
  database:
    url: "jdbc:mysql://localhost:3306/testdb_local"

---
# CI/CD Environment Profile  
spring:
  config:
    activate:
      on-profile: ci
automation:
  web:
    headless: true
    browser: chrome
  reporting:
    screenshots: true
    video-recording: true